---
- name: Atigeo Base
  hosts: hosts
  sudo: True 
  vars:

#  tasks:
#    - debug: msg="{{ ansible_default_ipv4.address }}"

##-- Uncomment the rolse you wish to install 
  roles:

##-- Add key chain to system in order for docker to trust-## 
## our geotrust keys.					  ##
##--------------------------------------------------------##

#    - trust-geotrust


##-- Docker role. ----------------------------------------##
## Variables: 						  ##
##	user: Adds the user to the docker group.          ##
##--------------------------------------------------------##

#    - { role: docker }


##-- Install java ----------------------------------------##
## Variables: 						  ##
##	java_location: Install directory, default         ##
## location is /usr/lib/jvm                               ##
##--------------------------------------------------------##

#    - { role: java  }


##-- Elastic search role ---------------------------------##
## Variables:  						  ##
##	data_dir: Direcotry for persistent storage.       ##
##                default direcotry is /data              ##
##--------------------------------------------------------##

#    - { role: elastic-search }


##-- Zookeeper role --------------------------------------##
## Variables:    					  ##
##	data_dir: Direcotry for persistent storage.       ##
##                default direcotry is /data              ##
##--------------------------------------------------------##

#    - { role: zookeeper }


##-- Kafka role ------------------------------------------##
## Requirements:					  ##
## 	Zookeeper running somewhere.			  ##
## Variables:						  ##
##	data_dir: Direcotry for persistent storage.       ##
##                default direcotry is /data              ##
##  	zookeeper_host: default is localhost.             ##
##--------------------------------------------------------##

#    - { role: kafka }


##-- Logstash role ---------------------------------------##
## Requirements:      					  ##
##	Elastic Search running somewhere.                 ##
## Variables:						  ##
##      data_dir: Direcotry for persistent storage.       ##
##                default direcotry is /data              ##
##--------------------------------------------------------##

#    - { role: logstash }


- hosts: spark
  sudo: True
  roles: 

##-- Install java ----------------------------------------##
## Variables:                                             ##
##      java_location: Install directory, default         ##
## location is /usr/lib/jvm                               ##
##--------------------------------------------------------##

    - { role: java  }


##-- Spark role ------------------------------------------##
## Requirments:                                           ##
##	Spark requires java installed on all hosts.       ##
## Variables:                                             ##
##      spark_master: host name of the spark-master-node. ##
##      spark_user: user name to run spark under.         ##
##--------------------------------------------------------##

    - { role: spark }


- hosts: nagios
  sudo: True
  roles:

##-- Install EPEL repo -----------------------------------##
## Variables:                                             ##
##--------------------------------------------------------##

    - { role: EPEL, when: "ansible_os_family == 'RedHat'" }


##-- Install nagios --------------------------------------##
## Variables:                                             ##
##--------------------------------------------------------##

    - { role: /home/grega/git/ansible-nagios }
