# docker role
- src: https://github.com/Atigeo/ansible-docker.git
  version: master
  name: docker

# trust-geotrust role
- src: https://github.com/Atigeo/ansible-trust-geotrust.git
  version: master
  name: trust-geotrust

# java role
- src: https://github.com/Atigeo/ansible-java.git
  version: master
  name: java

# Elastic-search role
- src: https://github.com/Atigeo/ansible-elastic-search.git
  version: master
  name: elastic-search

# Zookeeper role
- src: https://github.com/Atigeo/ansible-zookeeper.git
  version: master
  name: zookeeper

# Kafka role
- src: https://github.com/Atigeo/ansible-kafka.git
  version: master
  name: kafka

# Spark role
- src: https://github.com/Atigeo/ansible-spark.git
  version: master
  name: spark

# RedHat EPEL repos
- src: https://github.com/geerlingguy/ansible-role-repo-epel.git
  version: master
  name: EPEL

# Nagios role
- src: https://github.com/Atigeo/ansible-nagios.git
  version: master
  name: nagios

# Ganglia role
- src: https://github.com/Atigeo/atigeo-ganglia.git
  version: master
  name: ganglia

# Hadoop role
- src: https://github.com/Atigeo/ansible-hadoop.git
  version: master
  name: hadoop